# Basic
title: Brian S. Kim
subtitle: Today is the youngest you will ever be. Live like it.
description: Welcome to my life
avatarTitle: BK
avatarDesc: 22 years old
url: "https://bkskim.github.io"

permalink: /:year/:month/:title/
# Format

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

textColor: #FFFFFF

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
# blog_button:
   # title: Blog

# Navigation buttons in the front pages
nav:
    - {title: Blog, description: blog, url: 'https://medium.com/@bkskim'}   
    - {title: Projects, description: tags, url: '/tags'}   
    - {title: About, description: about, url: '/about'}

          
    

# Pagination
# gems: [jekyll-paginate]
# paginate: 20
# paginate_path: "page/:num/"






