theme: jekyll-theme-cayman
title: Welcome to Brian Kim's Website!
description: View BK's latest projects and blogs here

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "http://deanattali.com"
